# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 10:21
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_follows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthAccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=63)),
                ('name', models.CharField(max_length=255)),
                ('avatar', models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='')),
            ],
        ),
    ]
